version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        depends_on:
            - database
        ports:
            - '80:80'
        networks:
            - learnin_network
        entrypoint: sh -c "sleep 3 && php /var/www/html/artisan migrate && apache2-foreground"

    database:
        image: mariadb
        container_name: database
        restart: unless-stopped
        ports:
            - ${DB_PORT}:3306
        env_file:
            - ./.env
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - learnin_network

volumes:
    db_data:
networks:
    learnin_network:
